baseurl = "https://rodobarcaaa.github.io"
publishDir = "docs"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[params]
  mainSections = ["post"]
  logo = "img/profile.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true

[Author]
  name = "Rodolfo Echemendía Quintana"
  website = "rodobarcaaa.github.io"
  email = "rodobarcaaa@gmail.com"
  github = "rodobarcaaa"
  twitter = "rodobarcaaa"
  linkedin = "rechemendia"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    title = "Rodolfo's blog"
  [[languages.en.menu.main]]
    name = "Articles"
    url = ""
    weight = 1
  [[languages.en.menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2
  [[languages.en.menu.main]]
    name = "About me"
    url = "page/about/"
    weight = 3
  [languages.en.params]
    homeTitle = "Personal Tech Blog"
  [[languages.en.params.bigimg]]
    src = "img/sphere.jpg"
    position = "center top"

  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    title = "Blog de Rodolfo"
  [[languages.es.menu.main]]
    name = "Artículos"
    url = ""
    weight = 1
  [[languages.es.menu.main]]
    name = "Etiquetas"
    url = "tags"
    weight = 2
  [[languages.es.menu.main]]
    name = "Sobre Mi"
    url = "page/about/"
    weight = 3
  [languages.es.params]
    homeTitle = "Blog Personal de Tecnología"
  [[languages.es.params.bigimg]]
    src = "img/sphere.jpg"
    position = "center top"
